
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Jan 20 15:25:51 CST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int INT = 2;
  public static final int VOID = 3;
  public static final int DBL = 4;
  public static final int IF = 5;
  public static final int ELSE = 6;
  public static final int WHILE = 7;
  public static final int RETURN = 8;
  public static final int SCANF = 9;
  public static final int PRINTF = 10;
  public static final int INT_FORMAT = 11;
  public static final int DBL_FORMAT = 12;
  public static final int ID = 13;
  public static final int INTLITERAL = 14;
  public static final int DBLLITERAL = 15;
  public static final int STRINGLITERAL = 16;
  public static final int LCURLY = 17;
  public static final int RCURLY = 18;
  public static final int LPAREN = 19;
  public static final int RPAREN = 20;
  public static final int COMMA = 21;
  public static final int ASSIGN = 22;
  public static final int SEMICOLON = 23;
  public static final int PLUS = 24;
  public static final int MINUS = 25;
  public static final int STAR = 26;
  public static final int DIVIDE = 27;
  public static final int PLUSPLUS = 28;
  public static final int MINUSMINUS = 29;
  public static final int NOT = 30;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int EQUALS = 33;
  public static final int NOTEQUALS = 34;
  public static final int LESS = 35;
  public static final int GREATER = 36;
  public static final int LESSEQ = 37;
  public static final int GREATEREQ = 38;
  public static final int AMPERSAND = 39;
}

